directories:
  output: release/${version}
  buildResources: build
$schema: https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json
appId: com.crm.windows
asar: true
asarUnpack:
  - node_modules/better-sqlite3/**
productName: CRM Windows
files:
  - filter:
      - dist
      - dist-electron
      - node_modules/better-sqlite3/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: ${productName}-${version}-Setup.${ext}
nsis:
  oneClick: true
  perMachine: false
  deleteAppDataOnUninstall: false
electronVersion: 30.5.1
